name: tests on transformers PEFT main
on:
  push:
    branches:
    - main
env:
  CI_SLACK_CHANNEL: ${{ secrets.CI_PUSH_MAIN_CHANNEL }}
jobs:
  tests:
    strategy:
      matrix:
        python-version:
        - '3.9'
        - '3.10'
        - '3.11'
        os:
        - ubuntu-latest
        - windows-latest
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
        cache-dependency-path: 'setup.py

          requirements.txt

          '
    - name: Install dependencies
      run: "python -m pip install --upgrade pip\n# install PEFT & transformers from\
        \ source\npip install -U git+https://github.com/huggingface/peft.git\npip\
        \ install -U git+https://github.com/huggingface/transformers.git \n# cpu version\
        \ of pytorch\npip install \".[test, diffusers]\"\n"
    - name: Test with pytest
      run: 'make test

        '
    - name: Post to Slack
      if: always()
      uses: huggingface/hf-workflows/.github/actions/post-slack@main
      with:
        slack_channel: ${{ env.CI_SLACK_CHANNEL }}
        title: "\U0001F917 Results of the TRL CI on transformers/PEFT main"
        status: ${{ job.status }}
        slack_token: ${{ secrets.SLACK_CIFEEDBACK_BOT_TOKEN }}
